# Generated by Django 4.1.1 on 2022-09-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("tel", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
