# Generated by Django 4.1.1 on 2022-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("user_pw", models.CharField(max_length=20)),
                ("tel", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
            ],
        ),
    ]
