# Generated by Django 4.1.1 on 2022-09-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Member",),
    ]
